# Generated by Django 4.2.10 on 2025-05-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Проверено модератором'),
        ),
    ]
